<a href="https://colab.research.google.com/github/DaveWates/Extended-Learning-Portfolio/blob/main/Rainfall.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import csv

file = open('rainfall.csv')

type(file)
csvreader = csv.reader(file)
header = []
header = next(csvreader)
header
rows = []
for row in csvreader:
        rows.append(row)
rows

In [ ]:
import csv
rows = []
with open("rainfall.csv") as file:
    csvreader = csv.reader(file)
    header = next(csvreader)
    for row in csvreader:
        rows.append(row)

In [ ]:
import matplotlib.pyplot as plt
import csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("rainfall.csv")
df

    Year    Jan    Feb   Mar    Apr  ...    Sep   Oct   Nov   Dec  Annual
0   1993    NaN   27.6   5.8   14.6  ...   82.7   NaN   7.0   2.4     NaN
1   1994    1.6    0.2   3.8    4.2  ...   79.2  15.8   6.6   0.0   739.8
2   1995    0.0   12.0  20.0   10.8  ...   83.8  92.0  32.2   3.0   904.8
3   1996    3.2    0.0   9.2   27.0  ...  127.6  44.0  50.6  20.6   888.6
4   1997    0.6    3.6  53.8   38.6  ...  109.2  41.6   7.8   0.0   699.4
5   1998    1.8    0.0  43.0   15.2  ...   97.4  38.2  26.2  12.6   742.6
6   1999   48.2    0.0  28.6   30.2  ...  105.8  96.4   4.4   7.2   822.0
7   2000  139.0    0.0  22.2   32.6  ...   49.6   5.2  23.6   0.4   796.2
8   2001    2.4    7.0   2.8    7.4  ...  115.2  32.8  25.4   4.8   688.6
9   2002   18.4    8.2   2.6   96.0  ...   85.6  42.2  25.8   3.8   737.8
10  2003    1.4   11.0  61.4   49.0  ...  102.0  48.4  17.8   5.6   853.6
11  2004    0.0    2.0   0.0   12.0  ...   35.2  37.8  32.8   2.6   637.0
12  2005    0.0    3.0  52.2   27.8  ...   91.0  52.8  13.4   5.0   874.8
13  2006   28.4   20.6   4.6   25.4  ...   86.4  18.6  16.2   5.2   466.8
14  2007   19.2    3.4   6.2   76.4  ...  100.6  42.4   5.2  18.0   703.0
15  2008    0.0   47.6  14.2  153.6  ...   75.8  38.4  57.8  11.6   807.8
16  2009    0.2    8.2   6.8    5.0  ...   80.2   6.8  38.2   0.0   607.2
17  2010    0.0    0.2  40.4   25.0  ...   43.6  20.6  11.6  17.4   503.8
18  2011   30.2    0.4   0.0   19.4  ...  109.2  64.2  29.0  75.8   860.8
19  2012   18.8   23.6   0.2   69.2  ...   90.8  15.6  58.2  20.2   608.2
20  2013    7.2    0.8  69.6   21.0  ...  144.2  38.0  10.2   1.8   782.4
21  2014    0.2    0.0   7.4   24.6  ...   77.0  37.0  23.8   0.0   674.4
22  2015   18.6   23.4  15.6   54.0  ...   52.0  20.6  20.4  13.6   617.8
23  2016   15.2    0.6  16.8   68.2  ...   68.8  37.4  14.4  10.2   715.8
24  2017   45.4  137.2  23.6    0.0  ...   77.4  42.0   4.8  40.6   854.0
25  2018  106.2    0.2   2.6   20.6  ...   35.2  40.0   3.2   1.8   741.6
26  2019    7.2    0.2   6.2   44.2  ...   31.4   0.0  18.2   2.4     0.0
27  2020    3.0   34.4  32.8   13.2  ...   77.8  12.6  92.0   4.4   673.4

[28 rows x 14 columns]

In [ ]:
df

    Year    Jan    Feb   Mar    Apr  ...    Sep   Oct   Nov   Dec  Annual
0   1993    NaN   27.6   5.8   14.6  ...   82.7   NaN   7.0   2.4     NaN
1   1994    1.6    0.2   3.8    4.2  ...   79.2  15.8   6.6   0.0   739.8
2   1995    0.0   12.0  20.0   10.8  ...   83.8  92.0  32.2   3.0   904.8
3   1996    3.2    0.0   9.2   27.0  ...  127.6  44.0  50.6  20.6   888.6
4   1997    0.6    3.6  53.8   38.6  ...  109.2  41.6   7.8   0.0   699.4
5   1998    1.8    0.0  43.0   15.2  ...   97.4  38.2  26.2  12.6   742.6
6   1999   48.2    0.0  28.6   30.2  ...  105.8  96.4   4.4   7.2   822.0
7   2000  139.0    0.0  22.2   32.6  ...   49.6   5.2  23.6   0.4   796.2
8   2001    2.4    7.0   2.8    7.4  ...  115.2  32.8  25.4   4.8   688.6
9   2002   18.4    8.2   2.6   96.0  ...   85.6  42.2  25.8   3.8   737.8
10  2003    1.4   11.0  61.4   49.0  ...  102.0  48.4  17.8   5.6   853.6
11  2004    0.0    2.0   0.0   12.0  ...   35.2  37.8  32.8   2.6   637.0
12  2005    0.0    3.0  52.2   27.8  ...   91.0  52.8  13.4   5.0   874.8
13  2006   28.4   20.6   4.6   25.4  ...   86.4  18.6  16.2   5.2   466.8
14  2007   19.2    3.4   6.2   76.4  ...  100.6  42.4   5.2  18.0   703.0
15  2008    0.0   47.6  14.2  153.6  ...   75.8  38.4  57.8  11.6   807.8
16  2009    0.2    8.2   6.8    5.0  ...   80.2   6.8  38.2   0.0   607.2
17  2010    0.0    0.2  40.4   25.0  ...   43.6  20.6  11.6  17.4   503.8
18  2011   30.2    0.4   0.0   19.4  ...  109.2  64.2  29.0  75.8   860.8
19  2012   18.8   23.6   0.2   69.2  ...   90.8  15.6  58.2  20.2   608.2
20  2013    7.2    0.8  69.6   21.0  ...  144.2  38.0  10.2   1.8   782.4
21  2014    0.2    0.0   7.4   24.6  ...   77.0  37.0  23.8   0.0   674.4
22  2015   18.6   23.4  15.6   54.0  ...   52.0  20.6  20.4  13.6   617.8
23  2016   15.2    0.6  16.8   68.2  ...   68.8  37.4  14.4  10.2   715.8
24  2017   45.4  137.2  23.6    0.0  ...   77.4  42.0   4.8  40.6   854.0
25  2018  106.2    0.2   2.6   20.6  ...   35.2  40.0   3.2   1.8   741.6
26  2019    7.2    0.2   6.2   44.2  ...   31.4   0.0  18.2   2.4     0.0
27  2020    3.0   34.4  32.8   13.2  ...   77.8  12.6  92.0   4.4   673.4

[28 rows x 14 columns]

In [ ]:
df.iloc[27,  :].apply(np.sum)

Year      2020.0
Jan          3.0
Feb         34.4
Mar         32.8
Apr         13.2
May        111.6
Jun        115.4
Jul         83.4
Aug         92.8
Sep         77.8
Oct         12.6
Nov         92.0
Dec          4.4
Annual     673.4
Name: 27, dtype: float64

In [ ]:
df.iloc[0:27, :].apply(np.sum)

Year      54162.0
Jan         513.4
Feb         341.0
Mar         519.6
Apr         972.0
May        2343.4
Jun        3449.4
Jul        3901.6
Aug        3389.4
Sep        2236.9
Oct         968.8
Nov         584.8
Dec         286.6
Annual    18328.8
dtype: float64

In [ ]:
df.iloc[0:27, :].apply(np.min)

Year      1993.0
Jan          0.0
Feb          0.0
Mar          0.0
Apr          0.0
May         17.8
Jun         24.6
Jul         34.6
Aug         27.8
Sep         31.4
Oct          0.0
Nov          3.2
Dec          0.0
Annual       0.0
dtype: float64

In [ ]:
df.iloc[0:27, :].apply(np.mean)

Year      2006.000000
Jan         19.746154
Feb         12.629630
Mar         19.244444
Apr         36.000000
May         86.792593
Jun        127.755556
Jul        144.503704
Aug        125.533333
Sep         82.848148
Oct         37.261538
Nov         21.659259
Dec         10.614815
Annual     704.953846
dtype: float64

In [ ]:
df.columns = ['Year', 'Jan', 'Feb', 'Mar','Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Annual']
df.loc[0].apply(np.mean) , df.loc[1].apply(np.mean), df.loc[15].apply(np.mean)

(Year      1993.0
 Jan          NaN
 Feb         27.6
 Mar          5.8
 Apr         14.6
 May        129.6
 Jun         64.4
 Jul        123.2
 Aug        158.4
 Sep         82.7
 Oct          NaN
 Nov          7.0
 Dec          2.4
 Annual       NaN
 Name: 0, dtype: float64, Year      1994.0
 Jan          1.6
 Feb          0.2
 Mar          3.8
 Apr          4.2
 May         93.4
 Jun        203.4
 Jul        167.4
 Aug        164.2
 Sep         79.2
 Oct         15.8
 Nov          6.6
 Dec          0.0
 Annual     739.8
 Name: 1, dtype: float64, Year      2008.0
 Jan          0.0
 Feb         47.6
 Mar         14.2
 Apr        153.6
 May         59.6
 Jun        142.0
 Jul        179.4
 Aug         27.8
 Sep         75.8
 Oct         38.4
 Nov         57.8
 Dec         11.6
 Annual     807.8
 Name: 15, dtype: float64)

In [ ]:
# find the maximum values of each row
maxValues = df['Jan'].max()
print(maxValues)

139.0

In [ ]:
df.max(1)

In [ ]:
def ave_Yrly_RF():
 df_list = ['Jan', 'Feb', 'Mar','Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] 
 df['Ave Yearly Rain'] = df[df_list].mean(axis=1)
 return df

In [ ]:
def min_RF():
 df_list = ['Jan', 'Feb', 'Mar','Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] 
 df['Minimum Yearly Rain'] = df[df_list].min(axis=1)
 return df['Minimum Yearly Rain']

In [ ]:
def max_RF():
 df_list = ['Jan', 'Feb', 'Mar','Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] 
 df['Maximum Yearly Rain'] = df[df_list].max(axis=1)
 return df['Maximum Yearly Rain']

In [ ]:
ave_Yrly_RF()

    Year    Jan    Feb   Mar    Apr  ...   Oct   Nov   Dec  Annual  Ave Yearly Rain
0   1993    NaN   27.6   5.8   14.6  ...   NaN   7.0   2.4     NaN        61.570000
1   1994    1.6    0.2   3.8    4.2  ...  15.8   6.6   0.0   739.8        61.650000
2   1995    0.0   12.0  20.0   10.8  ...  92.0  32.2   3.0   904.8        75.400000
3   1996    3.2    0.0   9.2   27.0  ...  44.0  50.6  20.6   888.6        74.050000
4   1997    0.6    3.6  53.8   38.6  ...  41.6   7.8   0.0   699.4        58.283333
5   1998    1.8    0.0  43.0   15.2  ...  38.2  26.2  12.6   742.6        61.883333
6   1999   48.2    0.0  28.6   30.2  ...  96.4   4.4   7.2   822.0        68.500000
7   2000  139.0    0.0  22.2   32.6  ...   5.2  23.6   0.4   796.2        66.350000
8   2001    2.4    7.0   2.8    7.4  ...  32.8  25.4   4.8   688.6        57.383333
9   2002   18.4    8.2   2.6   96.0  ...  42.2  25.8   3.8   737.8        61.483333
10  2003    1.4   11.0  61.4   49.0  ...  48.4  17.8   5.6   853.6        71.133333
11  2004    0.0    2.0   0.0   12.0  ...  37.8  32.8   2.6   637.0        53.083333
12  2005    0.0    3.0  52.2   27.8  ...  52.8  13.4   5.0   874.8        72.900000
13  2006   28.4   20.6   4.6   25.4  ...  18.6  16.2   5.2   466.8        38.900000
14  2007   19.2    3.4   6.2   76.4  ...  42.4   5.2  18.0   703.0        58.583333
15  2008    0.0   47.6  14.2  153.6  ...  38.4  57.8  11.6   807.8        67.316667
16  2009    0.2    8.2   6.8    5.0  ...   6.8  38.2   0.0   607.2        50.600000
17  2010    0.0    0.2  40.4   25.0  ...  20.6  11.6  17.4   503.8        41.983333
18  2011   30.2    0.4   0.0   19.4  ...  64.2  29.0  75.8   860.8        71.733333
19  2012   18.8   23.6   0.2   69.2  ...  15.6  58.2  20.2   608.2        50.683333
20  2013    7.2    0.8  69.6   21.0  ...  38.0  10.2   1.8   782.4        65.200000
21  2014    0.2    0.0   7.4   24.6  ...  37.0  23.8   0.0   674.4        56.200000
22  2015   18.6   23.4  15.6   54.0  ...  20.6  20.4  13.6   617.8        51.483333
23  2016   15.2    0.6  16.8   68.2  ...  37.4  14.4  10.2   715.8        59.650000
24  2017   45.4  137.2  23.6    0.0  ...  42.0   4.8  40.6   854.0        71.166667
25  2018  106.2    0.2   2.6   20.6  ...  40.0   3.2   1.8   741.6        61.800000
26  2019    7.2    0.2   6.2   44.2  ...   0.0  18.2   2.4     0.0        46.866667
27  2020    3.0   34.4  32.8   13.2  ...  12.6  92.0   4.4   673.4        56.116667

[28 rows x 15 columns]